---
#-----------------------------------------------------
# PIPELINE STAGES
#-----------------------------------------------------

stages:
  - test
  - notify

#-----------------------------------------------------
# TEST: QA TEST
#-----------------------------------------------------

qa_test:
  stage: test
  only:
    - main
  variables:
    QA_ENVIRONMENT: "recette"
    WEB_DRIVER: "chrome"
  allow_failure: true
  before_script:
    - google-chrome --headless --disable-gpu --print-to-pdf https://www.chromestatus.com/ --no-sandbox
  script:
    # <<<<<<< HEAD
    # - mvn clean test -Dtest=RunCucumberTest
    - mvn clean -Denvironment=$QA_ENVIRONMENT -DwebDriver=$WEB_DRIVER test
    # - mvn clean test
    # =======
    #   - mvn clean test -Dtest=RunCucumberTest
    #- mvn clean -Denvironment=$QA_ENVIRONMENT -DwebDriver=$WEB_DRIVER test
    - mvn clean test
  # >>>>>>> a4e23c411b4e32e98a3af29d05e7aa2bf2e1afa1
  after_script:
    - ps aux | grep chrome | awk ' { print $2 } ' | xargs kill -9 || true
  artifacts:
    when: always
    name: "qa_report"
    paths:
      - target/reports/report.html
    expire_in: 1 h
  tags:
    - qa-runner

#-----------------------------------------------------
# TEST: QA NOTIFY
#-----------------------------------------------------

qa_notify:
  stage: notify
  only:
    - main
  script:
    - chmod +x ci/notify.sh
    - ./ci/notify.sh
  tags:
    - qa-runner
